namespace Ciir.Indexer.Core;

/// <summary>
/// The deterministic identity of a CIIR element ("sha256:&lt;64 hex chars&gt;"), preserved
/// integrally from the CIIR document per the CIIR contract - never regenerated by the indexer.
/// </summary>
public readonly record struct CiirIdentity
{
    public CiirIdentity(string value)
    {
        Value = Sha256Value.Validate(value, nameof(value));
    }

    public string Value { get; }

    public static implicit operator string(CiirIdentity identity) => identity.Value;

    public override string ToString() => Value;
}
