<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
    <PackageReference Include="FluentMigrator" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
    <PackageReference Include="BlogDoFT.Libs.DapperUtils.Postgres" Version="1.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ciir.Indexer.Application\Ciir.Indexer.Application.csproj" />
  </ItemGroup>

</Project>
